"""Generate TS types from api.models.deploy_events.DeployEvent.

Output: dashboard/src/lib/deploy-events.gen.ts

Run: python scripts/gen_deploy_event_types.py
"""

from __future__ import annotations

from pathlib import Path

from api.models.deploy_events import DeployEvent
from api.models.enums import DeployJobStatus

OUTPUT = Path(__file__).resolve().parents[1] / "dashboard/src/lib/deploy-events.gen.ts"


def _ts_field_type(name: str, prop: dict, required: bool) -> str:
    """Best-effort Pydantic JSON-schema -> TS type mapping for the DeployEvent shape."""
    # Required string fields (job_id, timestamp serialized as ISO string).
    if required:
        if "enum" in prop:
            return " | ".join(f'"{v}"' for v in prop["enum"])
        return "string"
    # Optional fields: union with null.
    if "enum" in prop:
        inner = " | ".join(f'"{v}"' for v in prop["enum"])
        return f"{inner} | null"
    # anyOf with null (Pydantic v2 emits Optional this way).
    if "anyOf" in prop:
        non_null = [a for a in prop["anyOf"] if a.get("type") != "null"]
        if non_null and "enum" in non_null[0]:
            inner = " | ".join(f'"{v}"' for v in non_null[0]["enum"])
            return f"{inner} | null"
        if non_null and non_null[0].get("type") == "integer":
            return "number | null"
        return "string | null"
    if prop.get("type") == "integer":
        return "number | null"
    return "string | null"


def main() -> None:
    schema = DeployEvent.model_json_schema()
    required_set = set(schema.get("required", []))
    fields: list[str] = []
    for name, prop in schema["properties"].items():
        ts_type = _ts_field_type(name, prop, required=name in required_set)
        fields.append(f"  {name}: {ts_type};")

    status_values = " | ".join(f'"{s.value}"' for s in DeployJobStatus)

    body = (
        "// AUTO-GENERATED by scripts/gen_deploy_event_types.py — do not edit by hand.\n"
        "// Source: api/models/deploy_events.py + api/models/enums.py::DeployJobStatus\n"
        "// Regenerate: python scripts/gen_deploy_event_types.py\n\n"
        'export type DeployEventType = "phase" | "log" | "complete" | "error";\n'
        "export type DeployPhase =\n"
        '  | "provisioning"\n'
        '  | "building"\n'
        '  | "pushing"\n'
        '  | "deploying"\n'
        '  | "health_checking"\n'
        '  | "registering";\n'
        f"export type DeployJobStatus = {status_values};\n\n"
        "export interface DeployEvent {\n" + "\n".join(fields) + "\n}\n"
    )
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(body)
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
