// AUTO-GENERATED by scripts/gen_deploy_event_types.py — do not edit by hand.
// Source: api/models/deploy_events.py + api/models/enums.py::DeployJobStatus
// Regenerate: python scripts/gen_deploy_event_types.py

export type DeployEventType = "phase" | "log" | "complete" | "error";
export type DeployPhase =
  | "provisioning"
  | "building"
  | "pushing"
  | "deploying"
  | "health_checking"
  | "registering";
export type DeployJobStatus = "pending" | "parsing" | "building" | "provisioning" | "deploying" | "health_checking" | "registering" | "completed" | "failed" | "pending_approval" | "pushing" | "timed_out";

export interface DeployEvent {
  type: "phase" | "log" | "complete" | "error";
  job_id: string;
  timestamp: string;
  phase: "provisioning" | "building" | "pushing" | "deploying" | "health_checking" | "registering" | null;
  step: number | null;
  total: number | null;
  message: string | null;
  level: "info" | "warn" | "error" | null;
  endpoint_url: string | null;
  error_code: string | null;
}
